<form action="index.php" method="post" name="formGrafar" id="formGrafar">
  <input type="hidden" name="action" id="action" value="salvar" />
  <input type="hidden" name="id" id="id" value="<?=$id?>" />
  <div id="divQuestion">
    <h3>Pergunta <?=$id + 1?></h3>
    <div>
      <textarea name="question" id="question" autofocus required><?=$question?></textarea>
    </div>
    <div>
      <select name="tag" id="tag" required>
        <option value=""></option>
        <option value="DI" <?=$tag == 'DI' ? 'selected' : ''?>>DI - Desenvolvimento de Informação
        </option>
        <option value="DS" <?=$tag == 'DS' ? 'selected' : ''?>>DS - Desenvolvimento de Software
        </option>
        <option value="ER" <?=$tag == 'ER' ? 'selected' : ''?>>ER - Engenharia de Computadores e
          Redes</option>
        <option value="ES" <?=$tag == 'ES' ? 'selected' : ''?>>ES - Engenharia de Software e
          Sistemas</option>
        <option value="GS" <?=$tag == 'GS' ? 'selected' : ''?>>GS - Garantia da Segurança de
          Sistemas</option>
        <option value="GT" <?=$tag == 'GT' ? 'selected' : ''?>>GT - Governança da Tecnologia e
          Serviços</option>
        <option value="LE" <?=$tag == 'LE' ? 'selected' : ''?>>LE - Legislação Geral e Específica
        </option>
        <option value="LI" <?=$tag == 'LI' ? 'selected' : ''?>>LI - Língua Inglesa</option>
        <option value="LP" <?=$tag == 'LP' ? 'selected' : ''?>>LP - Língua Portuguesa</option>
        <option value="MA" <?=$tag == 'MA' ? 'selected' : ''?>>MA - Matemática Básica e Aplicada
        </option>
        <option value="PE" <?=$tag == 'PE' ? 'selected' : ''?>>PE - Probabilidade e Estatística
        </option>
        <option value="RA" <?=$tag == 'RA' ? 'selected' : ''?>>RA - Raciocínio Lógico</option>
      </select>
    </div>
  </div>
  <hr>
  <div id="divAnswer">
    <h3>Resposta</h3>
    <div>
      <textarea name="answer" id="answer" required><?=$answer?></textarea>
    </div>
    <div>
      <input type="submit" value="Salvar" /> | <button type="button"
        onclick="numerar()">Numerar</button>
    </div>
  </div>
</form>
<script>
function numerar() {
  const answerEdit = document.getElementById('answer');
  let answer = answerEdit.value;
  let lines = answer.split("\n");
  for (let i = 0; i < lines.length; i++) {
    lines[i] = (i + 1) + ". " + lines[i].trim();
    if (!lines[i].endsWith(".") && !lines[i].endsWith(";")) {
      lines[i] += ".";
    }
  }
  answerEdit.value = lines.join("\n");
}

function random() {
  document.location = 'index.php?action=sortear&from=<?=$id?>';
}

function salvar(e) {
  e.preventDefault();
  e.stopPropagation();
  document.formGrafar.submit();
}
document.body.addEventListener("keydown", function(e) {
  if (e.altKey) {
    switch (e.key) {
      case "q":
        random();
        break;
    }
  } else if (e.ctrlKey) {
    switch (e.key) {
      case "s":
        salvar(e);
        break;
    }
  }
});
</script>