<form action="index.php" method="post" name="formGrafar" id="formGrafar">
  <input type="hidden" name="action" id="action" value="salvar" />
  <input type="hidden" name="id" id="id" value="<?=$id?>" />
  <input type="hidden" name="monitorar" id="monitorar" value="<?=$monitorar?>" />
  <div id="divQuestion">
    <h3>Pergunta <?=$id + 1?></h3>
    <div>
      <textarea name="question" id="question" autofocus required><?=$question?></textarea>
    </div>
    <div>
      <select name="tag" id="tag" required>
        <option value=""></option>
        <option value="DI" <?=$tag == 'DI' ? 'selected' : ''?>>DI - Desenvolvimento de Informação
        </option>
        <option value="DS" <?=$tag == 'DS' ? 'selected' : ''?>>DS - Desenvolvimento de Software
        </option>
        <option value="ER" <?=$tag == 'ER' ? 'selected' : ''?>>ER - Engenharia de Computadores e
          Redes</option>
        <option value="ES" <?=$tag == 'ES' ? 'selected' : ''?>>ES - Engenharia de Software e
          Sistemas</option>
        <option value="GS" <?=$tag == 'GS' ? 'selected' : ''?>>GS - Garantia da Segurança de
          Sistemas</option>
        <option value="GT" <?=$tag == 'GT' ? 'selected' : ''?>>GT - Governança da Tecnologia e
          Serviços</option>
        <option value="LE" <?=$tag == 'LE' ? 'selected' : ''?>>LE - Legislação Geral e Específica
        </option>
        <option value="LI" <?=$tag == 'LI' ? 'selected' : ''?>>LI - Língua Inglesa</option>
        <option value="LP" <?=$tag == 'LP' ? 'selected' : ''?>>LP - Língua Portuguesa</option>
        <option value="MA" <?=$tag == 'MA' ? 'selected' : ''?>>MA - Matemática Básica e Aplicada
        </option>
        <option value="PE" <?=$tag == 'PE' ? 'selected' : ''?>>PE - Probabilidade e Estatística
        </option>
        <option value="RA" <?=$tag == 'RA' ? 'selected' : ''?>>RA - Raciocínio Lógico</option>
      </select>
    </div>
  </div>
  <hr>
  <div id="divAnswer">
    <h3>Resposta</h3>
    <div>
      <textarea name="answer" id="answer" required><?=$answer?></textarea>
    </div>
    <div>
      <input type="submit" value="Salvar" /> | <button type="button"
        onclick="limpar()">Limpar</button> <button type="button"
        onclick="numerar()">Numerar</button> <button type="button"
        onclick="substituir()">Substituir</button> <button type="button"
        onclick="colar()">Colar</button> <button name="monitorarButton" id="monitorarButton"
        type="button" onclick="monitora()">Monitorar</button>
    </div>
  </div>
</form>
<script>
function limpar() {
  const alphanumeric = /^[\p{L}\p{N}]*$/u;
  const answerEdit = document.getElementById('answer');
  let answer = answerEdit.value;
  let lines = answer.split("\n");
  let index = 0;
  for (let l = 0; l < lines.length; l++) {
    let line = lines[l].trim()
    let start = -1;
    for (let i = 0; i < line.length; i++) {
      if (line.charAt(i).match(alphanumeric)) {
        start = i;
        break;
      }
    }
    if (start > -1) {
      line = line.substring(start);
    } else {
      line = "";
    }
    lines[l] = line;
  }
  answerEdit.value = lines.join("\n");
}

function numerar() {
  const answerEdit = document.getElementById('answer');
  let answer = answerEdit.value;
  let lines = answer.split("\n");
  let index = 0;
  for (let i = 0; i < lines.length; i++) {
    lines[i] = lines[i].trim()
    if (lines[i]) {
      lines[i] = (++index) + ". " + lines[i];
      if (!lines[i].endsWith(".") && !lines[i].endsWith(";")) {
        lines[i] += ".";
      }
    }
  }
  answerEdit.value = lines.join("\n");
}

function substituir() {
  let de = prompt("Substituir de:");
  if (de) {
    let para = prompt("Substituir para:");
    if (para) {
      const answerEdit = document.getElementById('answer');
      answerEdit.value = answerEdit.value.replaceAll(de, para);
    }
  }
}

function colar() {
  const tagEdit = document.getElementById('tag');
  const questionEdit = document.getElementById('question');
  const answerEdit = document.getElementById('answer');
  let reader = navigator.clipboard.readText();
  reader.then(text => {
    if (!text) {
      return;
    }
    if (!questionEdit.value) {
      questionEdit.value = text;
    } else {
      answerEdit.value = text;
      if (tagEdit.value) {
        salvar();
      }
    }
  });
}

function monitora() {
  if (document.getElementById('monitorar').value == '1') {
    return;
  }
  document.getElementById('monitorar').value = 1;
  const tagEdit = document.getElementById('tag');
  const questionEdit = document.getElementById('question');
  const answerEdit = document.getElementById('answer');
  const monitorarButton = document.getElementById('monitorarButton');
  monitorarButton.innerText = 'Monitorando';
  var monitor_last_one = -1;
  setInterval(() => {
    navigator.clipboard.readText().then(text => {
      if (monitor_last_one === -1) {
        monitor_last_one = text;
        return;
      }
      if (monitor_last_one != text) {
        monitor_last_one = text;
        if (!questionEdit.value) {
          questionEdit.value = text;
        } else {
          answerEdit.value = text;
          if (tagEdit.value) {
            salvar();
          }
        }
      }
    }).catch(() => {});
  }, 1000);
}

function random() {
  document.location = 'index.php?action=sortear&from=<?=$id?>';
}

function salvar() {
  document.formGrafar.submit();
}

function previne(e) {
  if (e.preventDefault) {
    e.preventDefault();
  }
  if (e.stopPropagation) {
    e.stopPropagation()
  }
}
document.body.addEventListener("keydown", function(e) {
  if (e.altKey) {
    switch (e.key) {
      case "q":
        previne(e);
        random();
        break;
      case "l":
        previne(e);
        limpar();
        break;
      case "n":
        previne(e);
        numerar();
        break;
      case "s":
        previne(e);
        substituir();
        break;
      case "v":
        previne(e);
        colar();
        break;
    }
  } else if (e.ctrlKey) {
    switch (e.key) {
      case "s":
        previne(e);
        salvar();
        break;
    }
  }
});
if (document.getElementById('monitorar').value == '1') {
  setTimeout(() => {
    document.getElementById('monitorar').value = 0;
    monitora();
  }, 300);
}
</script>