 <div id="divQuestion">
   <h3>Pergunta <?=$id + 1?> - (<?=$tag?>)</h3>
   <div>
     <p><?=$question?></p>
   </div>
   <div><button onclick="respond()">Responder</button></div>
 </div>
 <hr>
 <div id="divAnswer" style="display: none;">
   <h3>Resposta</h3>
   <div>
     <p><?=$answer?></p>
   </div>
   <div><button onclick="grafar()">Grafar</button>
   </div>
 </div>
 <script>
function respond() {
  document.getElementById('divAnswer').style.display = 'block';
}

function grafar() {
  document.location = 'index.php?action=grafar&id=<?=$id?>';
}

function random() {
  document.location = 'index.php?action=sortear&from=<?=$id?>';
}

var shouldRespond = true;
var shouldRandom = true;

function stopAutomatic() {
  shouldRespond = false;
  shouldRandom = false;
}

setTimeout(function () {
  if (shouldRespond) {
    respond();
  } 
}, 30 * 1000);

setTimeout(function () {
  if (shouldRandom) {
    random();
  } 
}, 2 * 60 * 1000);

document.body.addEventListener("keyup", function(e) {
  if (e.altKey) {
    switch (e.key) {
      case "r":
        respond();
        break;
      case "g":
        grafar();
        break;
      case "q":
        random();
        break;
      case "z":
        stopAutomatic();
        break;
    }
  }
});
 </script>