 <div id="divQuestion">
   <h3>Pergunta <?=$id + 1?> - (<?=$tag?>)</h3>
   <div>
     <p><?=$question?></p>
   </div>
   <div><button onclick="responder()">Responder</button></div>
 </div>
 <hr>
 <div id="divAnswer" style="display: none;">
   <h3>Resposta</h3>
   <div>
     <p><?=$answer?></p>
   </div>
   <div><button onclick="grafar()">Grafar</button>
   </div>
 </div>
 <script>
function responder() {
  document.getElementById('divAnswer').style.display = 'block';
}

function grafar() {
  document.location = 'aptar.php?action=grafar&id=<?=$id?>';
}
 </script>