<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="aptar.css">
  <title>Pointel - Aptar</title>
</head>

<body>
  <h1>Pointel - Aptar</h1>
  <table>
    <thead>
      <tr>
        <th>Id</th>
        <th>Tags</th>
        <th>Question</th>
        <th>Answer</th>
      </tr>
    </thead>
    <tbody> <?php foreach ($data as $row): ?> <tr>
        <td><?=$row['id']?></td>
        <td><?=$row['tags']?></td>
        <td><?=$row['question']?></td>
        <td><?=$row['answer']?></td>
      </tr> <?php endforeach?> </tbody>
  </table>
</body>

</html>