<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="aptar.css">
  <title>Pointel - Aptar</title>
</head>

<body>
  <h1>Pointel - Aptar</h1>
  <h2>
    <a href="aptar.php?action=listar">Listar</a> - <a href="aptar.php?action=grafar">Grafar</a> -
    <a href="aptar.php?action=sortear">Sortear</a>
  </h2> <?php
include 'aptar-' . $action . '.php';
include 'aptar-' . $action . '.phtml';
?>
</body>

</html>