<form action="index.php" method="post">
  <input type="hidden" name="action" id="action" value="salvar" />
  <input type="hidden" name="id" id="id" value="<?=$id?>" />
  <div id="divQuestion">
    <h3>Pergunta <?=$id + 1?></h3>
    <div>
      <textarea name="question" id="question" autofocus required><?=$question?></textarea>
    </div>
    <div>
      <select name="tag" id="tag" required>
        <option value=""></option>
        <option value="DI" <?=$tag == 'DI' ? 'selected' : ''?>>DI - Desenvolvimento de Informação</option>
        <option value="DS" <?=$tag == 'DS' ? 'selected' : ''?>>DS - Desenvolvimento de Software</option>
        <option value="ER" <?=$tag == 'ER' ? 'selected' : ''?>>ER - Engenharia de Computadores e Redes</option>
        <option value="ES" <?=$tag == 'ES' ? 'selected' : ''?>>ES - Engenharia de Software e Sistemas</option>
        <option value="GS" <?=$tag == 'GS' ? 'selected' : ''?>>GS - Garantia da Segurança de Sistemas</option>
        <option value="GT" <?=$tag == 'GT' ? 'selected' : ''?>>GT - Governança da Tecnologia e Serviços</option>
        <option value="LE" <?=$tag == 'LE' ? 'selected' : ''?>>LE - Legislação Geral e Específica</option>
        <option value="LI" <?=$tag == 'LI' ? 'selected' : ''?>>LI - Língua Inglesa</option>
        <option value="LP" <?=$tag == 'LP' ? 'selected' : ''?>>LP - Língua Portuguesa</option>
        <option value="MA" <?=$tag == 'MA' ? 'selected' : ''?>>MA - Matemática Básica e Aplicada</option>
        <option value="PE" <?=$tag == 'PE' ? 'selected' : ''?>>PE - Probabilidade e Estatística</option>
        <option value="RA" <?=$tag == 'RA' ? 'selected' : ''?>>RA - Raciocínio Lógico</option>
      </select>
    </div>
  </div>
  <hr>
  <div id="divAnswer">
    <h3>Resposta</h3>
    <div>
      <textarea name="answer" id="answer" required><?=$answer?></textarea>
    </div>
    <div><input type="submit" value="Salvar" /></div>
  </div>
</form>