<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Tag</th>
      <th>Pergunta</th>
      <th>Resposta</th>
    </tr>
  </thead>
  <tbody> <?php foreach ($data as $id => $row): ?> <tr>
      <td><a href="index.php?action=grafar&id=<?=$id?>"><?=$id + 1?></a></td>
      <td><?=$row['tag']?></td>
      <td><?=$row['question']?></td>
      <td><?=$row['answer']?></td>
    </tr> <?php endforeach?> </tbody>
</table>