<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/main.css">
  <link rel="stylesheet" href="index.css">
  <title>Pointel - Aptar (Power Intelligence)</title>
</head>

<body>
  <div id="topPointel">
      <img src="/assets/pointel.png" />
      <h1><a href="https://www.pointel.com.br/">Pointel</a></h1>
      <h2><a href="index.php">Aptar</a></h2>
  </div>
  <h3><a href="index.php?action=listar">Listar</a> | <a href="index.php?action=grafar">Grafar</a> |
    <a href="index.php?action=sortear">Sortear</a></h3> <?php
require 'act-' . $action . '.php';
require 'act-' . $action . '.phtml';
?> <script>
  document.body.addEventListener("keyup", function(e) {
    if (e.altKey && e.key == "a") {
      document.location = "index.php?action=listar";
    } else if (e.altKey && e.key == "s") {
      document.location = "index.php?action=sortear";
    } else if (e.altKey && e.key == "c") {
      document.location = "index.php?action=grafar";
    }
  });
  </script>
</body>

</html>