<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/main.css">
  <link rel="stylesheet" href="index.css">
  <title>Pointel - Aptar (Power Intelligence)</title>
</head>

<body>
  <div>
    <a href="index.php">
      <img src="/assets/pointel.png" style="height: 36px; width: 36px;" />
      <h1>Pointel</h1>
      <h2>Aptar</h2>
    </a>
  </div>
  <h3><a href="index.php?action=listar">Listar</a> | <a href="index.php?action=grafar">Grafar</a> |
    <a href="index.php?action=sortear">Sortear</a></h3> <?php
require 'act-' . $action . '.php';
require 'act-' . $action . '.phtml';
?> <script>
  document.body.addEventListener("keyup", function(e) {
    if (e.altKey && e.key == "s") {
      document.location = "index.php?action=sortear";
    }
  });
  </script>
</body>

</html>