<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="index.css">
  <title>Pointel - Aptar</title>
</head>

<body>
  <h1>Pointel - Aptar</h1>
  <h2><a href="index.php?action=listar">Listar</a> | <a href="index.php?action=grafar">Grafar</a> ^
  </h2>
  <h2><a href="index.php?action=sortear">Sortear</a> * </h2> <?php
require 'act-' . $action . '.php';
require 'act-' . $action . '.phtml';
?> <script src="index.js"></script>
</body>

</html>